name: Music replacements for Reach out to the Truth
id: pq2.audio.musicreplacements
author: darkitxu84
link: https://jacksexo.hd
version : "1.0.0"
description: Replaces the original version of Reach out to the Truh with a selected one.
